component "rubygem-net-netconf" do |pkg, settings, platform|
  pkg.version "0.4.3"
  if platform.is_huaweios?
    # This tarball was generated by doing a puppet-agent build without
    # net-netconf but including its dependencies (nokogiri), installing
    # it on the target, and installing the net-netconf gem using our gem
    # command. The added files from :gem_home were then tar'ed up and
    # packed into this container tarball.
    pkg.url "http://buildsources.delivery.puppetlabs.net/net-netconf-#{pkg.get_version}.tar.gz"
    pkg.md5sum "73ba0faadf9f3e3fcc8d9307b0ba4fa2"
  else
    pkg.url "http://buildsources.delivery.puppetlabs.net/net-netconf-#{pkg.get_version}.gem"
    pkg.md5sum "fa173b0965766a427d8692f6b31c85a4"
  end

  pkg.build_requires "ruby"
  pkg.build_requires "rubygem-nokogiri"
  pkg.build_requires "rubygem-net-scp"

  if platform.is_huaweios?
    # The "gem install net-netconf" method of installing the gem won't work
    # for cross-compiled platforms, because this gem depends on nokogiri.
    # The gem installation process will see that nokogiri extensions do not
    # exist for the native platform and then try to build them, which is not
    # what we want. So instead we use a tarball of files used from an install
    # run in the target environment.
    pkg.install do
      ["tar xvf net-netconf_files.tar -C #{settings[:gem_home]}"]
    end
  else
    pkg.install do
      ["#{settings[:gem_install]} net-netconf-#{pkg.get_version}.gem"]
    end
  end
end
