dist: bionic
sudo: false
services:
  # bionic uses 18.06 but need 19.03+ so upgrade later in relevant cell
  - docker
git:
  depth: 150
language: ruby
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  - gem update --system --force
before_script:
  - 'git config --global user.email "you@example.com"'
  - 'git config --global user.name "Your Name"'
script: "bundle exec rake $CHECK"
notifications:
  email: false

matrix:
  include:
    - stage: puppet-agent lint
      rvm: 2.5
      env: "CHECK=rubocop"
    - stage: puppet-agent lint
      rvm: 2.5
      env: "CHECK=commits"
    - stage: puppet-agent container tests
      language: ruby
      rvm: 2.5.5
      env:
        - DOCKER_COMPOSE_VERSION=1.24.0
        # necessary to prevent overwhelming TravisCI build output limits
        - DOCKER_BUILD_FLAGS="--progress plain"
      script:
        - |
          set -ex
          sudo apt update -y && sudo apt install -y docker.io
          sudo systemctl unmask docker.service
          sudo systemctl start docker
          sudo rm /usr/local/bin/docker-compose
          curl --location https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname --kernel-name`-`uname --machine` > docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin
          cd docker
          make lint
          make build
          make test
          set +x
