#! /usr/bin/env ruby

require 'fileutils'
require 'open3'

FileUtils.rm_rf(File.join(Dir.pwd, 'output'))

Open3.popen2e('docker', 'build', '-f', 'Dockerfile.build', '-t', 'puppet/puppet-agent-alpine:build', '.') do |stdin, output_stream, wait_thread|
  output_stream.each_line do |line|
    puts line
  end
end


Open3.popen2e('docker', 'run', '-v', "#{File.join(Dir.pwd, 'output')}:/srv", '--rm', 'puppet/puppet-agent-alpine:build', 'cp', '-a', '/usr/lib/ruby/vendor_ruby/facter.rb', '/etc/puppetlabs', '/usr/local/share', '/usr/local/bin', '/usr/local/lib', '/usr/lib/ruby/gems', '/srv') do |stdin, output_stream, wait_thread|
  output_stream.each_line do |line|
    puts line
  end
end


Open3.popen2e('docker', 'build', '-t', 'puppet/puppet-agent-alpine:test', '.') do |stdin, output_stream, wait_thread|
  output_stream.each_line do |line|
    puts line
  end
end

FileUtils.rm_rf(File.join(Dir.pwd, 'output'))
