---
HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vmpooler
    template: redhat-7-x86_64
  pe-aix-53-acceptance:
    roles:
      - agent
    platform: aix-5.3-power
    hypervisor: none
    vmhostname: pe-aix-53-acceptance.delivery.puppetlabs.net 
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
